[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# [build]
#   command   = "npm run build"
#   functions = "out_functions"
#   publish   = "out_publish"

# [[plugins]]
# package = "netlify-plugin-inline-functions-env"
#   [plugins.inputs]
#   buildEvent = "onBuild"
